# Generated by Django 5.2.4 on 2025-07-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0007_userprofile_referral_code_userprofile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discount_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
    ]
