# Generated by Django 5.2.4 on 2025-07-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0008_userprofile_discount_used_userprofile_referral_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
