# Generated by Django 5.2.4 on 2025-07-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0011_customuser_referral_code_customuser_referral_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
    ]
