# Generated by Django 5.2.4 on 2025-07-16 11:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0012_remove_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='previous_profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
