# Generated by Django 5.2.4 on 2025-07-16 11:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0013_userprofile_previous_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='previous_profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='previous_profile_picture'),
        ),
    ]
