# Generated by Django 5.2.4 on 2025-07-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0015_alter_userprofile_previous_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
