# Generated by Django 5.2.4 on 2025-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0019_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
